### ISSUE TITLE
Extension for Firefox doesn't work anymore?

### ISSUE THREAD

**Issue by KORraNpl** [pocc/no-wysiwyg#3] opened 2019-12-18 08:46 UTC
At least for me. WYSIWYG buttons are visible, using markup triggers changing text immediately.
MacOS 10.14.6
Firefox 72 beta 7

**Comment by pocc** [comment] 2019-12-18 21:52
Duplicate of https://github.com/kfahy/slack-disable-wysiwyg-bookmarklet/issues/27. The script this extension is based off of no longer works. Given that you can enable markup (and disable wysiwyg behavior with a setting), I would do that instead. More details on how to access that setting can be found on the script's page: https://github.com/kfahy/slack-disable-wysiwyg-bookmarklet.

**Comment by KORraNpl** [comment] 2019-12-19 15:43
Yes, I know that they've added this option. However, enabling markup turns off formatting keyboard shortcuts for me, i.e. I can't paste some text, select it and press CTRL + Shift + C (to make it formatted as code) or CTRL + Shift + > (quote)...

But it seems there is no way back, I guess.

**Comment by pocc** [comment] 2019-12-20 01:32
Slack disabled pushing redux settings from client scripts (including the wysiwyg "experiment"). If you can modify kfahy's script to get around this new limitation, I would be happy to merge.

**Comment by pocc** [comment] 2019-12-21 21:33
@KORraNpl Trying to understand what you're trying to do. Wouldn't using the markup setting do what you're suggesting (paste some code and have it autoformatted on enter)? Please be as explicit as possible.

**Comment by KORraNpl** [comment] 2019-12-22 21:32
That's the thing - with markup formatting enabled, keyboard shortcuts doesn't work. They work only in WYSIWYG mode, which I don't like for a few reasons:
* text jumps around when formatting
* it automatically adds formatting to next line (i.e. extending list), which is not always what I want
* at the moment I'm unable to create code block: CTRL + ALT + SHIFT + C (which used to be simply CTRL + SHIFT +C, by the way) doesn't work with my locale (I get "Ć"). If I try to prepend ``` at the beginning of pasted code, it changes first line to code block, but it's impossible extend the block of the rest of lines. Sure, there is a button for code block, but personally I prefer keyboard shortcuts.

In the end, it's Slack, I don't think it's worth to try to hack it again if they may break some functionality again in next update. Feel free to close this issue :)

**Comment by pocc** [comment] 2019-12-28 20:51
I guess this is fine. It's probably possible to disable event listeners for key strokes and readd them on enter, but it's true that Slack at the end of the day can change their UI any way they want.

**Closed as completed by pocc** 2019-12-28 20:51 UTC
